config/routes.rb
Rails.application.routes.draw do
  post 'best_answers/best', as: :best
  resources :notes, only: :show
  root 'notes#index'
end

app/models/best_answer.rb
class BestAnswer < ActiveRecord::Base
  belongs_to :note
  belongs_to :comment
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :note
end

app/models/note.rb
class Note < ActiveRecord::Base
  has_many :comments
  has_one :best_answer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/best_answers_controller.rb
class BestAnswersController < ApplicationController
  def best
    note = Note.find(params[:note_id])
    bestanswer = note.build_best_answer(comment: params[:comment])
    bestanswer.save
    redirect_to note, notice: 'hogehoge'
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/best_answers_helper.rb
module BestAnswersHelper
end

app/helpers/note_helper.rb
module NoteHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BacktraceSandbox</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notes/index.html.erb
<h1>Note#index</h1>
<ul>
  <% @notes.each do |note| %>
    <li><%= link_to note.body, note_path(note) %></li>
  <% end %>
</ul>

app/views/notes/show.html.erb
<h1>Note#show</h1>
<p>Comments</p>
<ul>
<% @note.comments.each do |comment| %>
  <li>
    <%= comment.body %>
    <% if @note.best_answer.try(:comment) == comment %>
      <b>(BA)</b>
    <% else %>
      <%= link_to "BAに決定", best_path(:comment => comment.id, :note_id => @note.id), method: :post %>
    <% end %>
  </li>
<% end %>
</ul>
<%= link_to 'Back', root_path %>